name: censorx
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - flask-cors
  - gunicorn
  - scikit-learn
  - pandas
  - numpy
  - pytorch 
  - torchvision
  - pip
  - pip:
      - transformers>=4.30.0  
      - torchao
      - tensorflow 
      - google-cloud-storage