# environment.yml
name: censorx
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - flask-cors
  - gunicorn
  - scikit-learn
  - pandas
  - numpy
  - tensorflow
  - pytorch
  - torchvision
  - pip
  - pip:
      - transformers
      - torchao