name: censorx
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  # Core Web and Data Science
  - flask
  - flask-cors
  - gunicorn
  - scikit-learn
  - pandas
  - numpy=1.26.4
  - tqdm
  - python-dotenv
  
  # PyTorch CPU (install via conda for better compatibility)
  - pytorch=2.5.1
  - torchvision=0.20.1
  - cpuonly
  
  - pip:
      - sympy         
      - safetensors
      - torchao==0.6.1
      
      # Transformers & ML Tools
      - transformers>=4.40.0
      - tensorflow
      - torchserve
      - torch-model-archiver
      
      # Google Cloud & gRPC
      - protobuf>=4.25.3
      - grpcio>=1.50.0
      - grpcio-status>=1.50.0
      - google-cloud-storage
      - google-auth
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-api-python-client